---
driver:
  name: molecule-proxmox
  options:
    proxmox_secrets: $HOME/.molecule/proxmox-secrets.yml
    full: true

platforms:
  - name: "molecule-${os}"
    template_name: ${os}-tmp
    ipconfig:
      ipconfig0: 'ip=dhcp'

provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        wireguard_server_ip: "10.10.0.1/24"
        wireguard_server_port: 50500
        wireguard_dns: "8.8.8.8"
        wireguard_peers:
          - "user1"
          - "user2"
  env:
    ANSIBLE_VERBOSITY: 3
  lint:
    name: "ansible-lint"
