---
- name: Generate the WireGuard private and public keys
  shell: |
    umask 077
    wg genkey | tee server-private.key | wg pubkey > server-public.key
  args:
    chdir: /etc/wireguard
    creates: /etc/wireguard/server-public.key
  changed_when: false

- name: Get the WireGuard private key
  command: "cat /etc/wireguard/server-private.key"
  register: server_private_key

- name: Get the WireGuard public key
  command: "cat /etc/wireguard/server-public.key"
  register: server_public_key